---
# tasks file for Memcached
# ---
- name: create my_counter_metric
  osdk_metric:
    name: my_counter_metric2
    description: Random counter metric
    counter: {}

- name: increment my_counter_metric
  osdk_metric:
    name: my_counter_metric
    description: Random counter metric
    counter:
      increment: yes

- name: add 3.14 to my_counter_metric
  osdk_metric:
    name: my_counter_metric
    description: Random counter metric
    counter:
      add: 3.14
- name: increment my_counter_metric
  osdk_metric:
    name: my_counter_metric
    description: Random counter metric
    counter:
      increment: yes
- name: add 3.14 to my_counter_metric
  osdk_metric:
    name: my_counter_metric
    description: Random counter metric
    counter:
      add: 3.14
- name: add 3.14 to my_counter_metric2
  osdk_metric:
    name: my_counter_metric2
    description: Random counter metric
    counter:
      add: 3.14
- name: subtract
  osdk_metric:
    name: my_counter_metric2
    description: Random counter metric
    counter:
      add: -3.14
